### PR TITLE
Extended docs for "Parsing JSON Requests"

### PR DESCRIPTION
**Pull request by rubenjr0**
I couldn't replicate the `SerializedInvoice` example of the docs on a project of mine.

I've extended the example with information provided on the Discord server.

### CODE REVIEW

**Review by jwoertink — APPROVED** [review]
Awesome! Thanks for adding this.

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by jwoertink** [comment]
Looks like there's still some trailing whitespace. You can run `./bin/ameba` locally to check these @rubenjr0 Once those are resolved, this should be good to go

**Comment by rubenjr0** [comment]
> Looks like there's still some trailing whitespace. You can run `./bin/ameba` locally to check these @rubenjr0 Once those are resolved, this should be good to go

Done, thanks for the patience and apologies for taking so long with such a simple thing

**Comment by jwoertink** [comment]
@rubenjr0 no worries at all! We appreciate you updating this.

**Pull request merged**
