### PR TITLE
Upgrade TailwindCSS

### LINKED ISSUE #297: Upgrade tailwind and use purge option
https://twitter.com/adamwathan/status/1255601129267830784?s=20

Would be great to purge most of the css with this option but we need to make sure all the pages still look good to ensure it didn’t remove classes we use

### PR DESCRIPTION
**Pull request by stephendolan**
Well... this turned into quite a feisty little PR to wrangle! It aims to close #297.

Let's dig in!

### The process

For every commit to the TailwindCSS config file (https://github.com/luckyframework/website/commits/master/tailwind.config.js), I essentially replayed that change into the new config format.

### Major changes

1. Colors changed from "darkest" -> "dark" gradients to numerical gradients "800" -> "700". Rather than updating every use of color in our site, I copied the old color scheme (omitting unused colors) into our custom config. At some point I do think it would be worth transitioning entirely to the default colors + "Lucky Blue", but that can be done later.

1. Text tracking changed slightly to add some intermediate values. We had added a "medium" tracking setting manually (https://github.com/luckyframework/website/commit/e0288b217faab9c8f4e1faccba7226c554dddf49#diff-8927db3d5d9a070423893c3ca4c68042), which is no longer necessary with the new "wide" and "wider" values (https://tailwindcss.com/docs/letter-spacing). To resolve this, I leveraged the following substitutions (verified in git diff manually):
    - `rg "tracking-wide" -l | xargs sed -E -i '' 's/tracking-wide(["\s])/tracking-wider\1/g'`
    - `rg "tracking-medium" -l | xargs sed -i '' 's/tracking-medium/tracking-wide/g'`

1. We're using PurgeCSS now! I verified that when manually enabled, my bundle size for `app.css` went down from **2 MB** to only **50.6 KB**, which is awesome! I've turned off that "on" switch so that PurgeCSS will correctly only apply in a production Node environment.

### Visual Verification

I'm going to add some screens below to assist, but I'd recommend building a branch and poking around a bit. I visited every variation of pages I could find (guides, blog posts, home page, etc), but a second (or third) set of eyes would be good!

At the very least, nothing is so off that it's noticeable to me, and the site still loads. Success!

Anyhow, here are some screenshots to compare a few key pages:
**Home Before**
home_before

**Home After**
home_after

**Mobile Home Before**
mobile_home_before

**Mobile Home After**
mobile_home_after

**Guides Before**
guides_before

**Guides After**
guides_after

### CODE REVIEW

**Comment by paulcsmith** [comment]
I deployed a review app at https://lucky-websit-upgrade-ta-linuju.herokuapp.com for anyone to take a look. @edwardloveall @jwoertink when you have a moment could you go through and check for any visual issues?

@stephendolan Thank you so much for the thorough writeup and description. I'll try to get to the actual code review soon!

**Comment by paulcsmith** [comment]
Also, this bumped performance numbers on lighthouse from 78 to 94!!

Before:
Screen Shot 2020-08-13 at 1 31 24 PM

After:
Screen Shot 2020-08-13 at 1 31 50 PM

There are a few more optimizations to make but this site is 🔥 now

**Comment by edwardloveall** [comment]
Looks great. I couldn't find anything significant. Just tiny spacing changes slight color adjustments. I saw this weird underline under the lucky version in the guides, but it's there in the original site also so not really the fault of this PR.

**Comment by paulcsmith** [comment]
@edwardloveall why you hatin on my line? 😂 But seriously it does look a bit weird when in the getting started section. i think it makes more sense in the other sections though to clarify it is not a clickable section.

Screen Shot 2020-08-14 at 11 03 04 AM

Ideally though that'd be a dropdown with a version selector (one day!)

**Comment by paulcsmith** [comment]
I think this looks great. Thanks @stephendolan !

**Pull request merged**
