### PR TITLE
Add 'Building Something Real' Section

### PR DESCRIPTION
**Pull request by stephendolan**
This is intended to be a discussion point for whether or not the core team is open to something like this before I spend too much time on it.

The inspiration for this section comes from the StimulusJS documentation's [Building Something Real](https://stimulusjs.org/handbook/building-something-real) section, which I find myself coming back to again and again.

**Couldn't/shouldn't this just be a personal blog post?**

Maybe, and I'm definitely open to that! If this PR is rejected I still intend to copy & paste the content into [my blog](https://stephencodes.com/blog) to make it available. I think that the benefits of having a _single_ full picture into using Lucky adds value for several reasons, though:

1. In a web framework, _context is key_. When I was first getting started, I found myself searching the Lucky site constantly as I moved through my application. Having to jump around between pages left me sometimes feeling like there were gaps that I just wasn't getting, wondering if I'd missed or forgotten some subsection of the "HTML" section that talked through passing operations to pages, for example. A single, simple app would tell the entire story of the _simplest_ Lucky development path, which could act as the "glue" that I believe a lot of newcomers would benefit from.
1. This allows developers to "follow along" and explore Lucky without having to install and set everything up locally, as easy as Lucky does make that. I believe that it's hard to grasp the power of Lucky with the current documentation fully, since you'd have to read through the entirety to see some of the benefits of the framework as a whole.
1. Developers would have an "official" reference app for the "Lucky way" of building an app. Once I had my first Lucky app up and running, I essentially switched from parsing through the Guides to referencing my application to remember things like how to set up my forms, how to mount a component, how to render HTML from an action, etc. Had something like this existed, it would have sped up the development of that first app, and also would have been bookmarked as my reference point for future apps.
1. The path for exploring the framework in a detailed, component-by-component way is currently really elegant in the documentation, but an overview with optional deep dives is more difficult. Linking out to key guide sections during the normal flow of building an app will provide a better experience for potential users who learn better with the latter method.

I'm not sure whether the Heroku preview apps for PRs are currently set up for this repo or not, so I'll drop a screenshot below to give passers-by a glimpse into what I've put together so far:

lucky_building_something_real

### CODE REVIEW

**Comment by jwoertink** [comment]
I love the idea, and I know we've talked about having something like this. My thought is that this would go within the "cookbook" type section as mentioned here https://github.com/luckyframework/website/issues/313 though a link to it in the getting started does make sense.

Thank you for starting this. I'd say don't close this, but also maybe hold off a little until we see what @paulcsmith says.

**Comment by stephendolan** [comment]
Sure thing, @jwoertink ! It's just something that's been on my mind this week that I needed to get out, and I'm happy to let this sit for a bit to explore some options with you and @paulcsmith .

**Comment by edwardloveall** [comment]
Thanks for doing this @stephendolan! This is a great idea.

**Comment by paulcsmith** [comment]
I 1000% agree that we need something like this and I think putting it in the "Getting Started" is a great idea!

I started something a long time ago and never finished https://gist.github.com/paulcsmith/d9855fe109d3b7c6fd78a9446e61823a. Maybe this could serve as a starting point, but feel free to modify and go in a different direction. I'm so excited about this and I think this will really help new people. Building something is how I like to learn and I bet I'm not alone in that!

**Comment by stephendolan** [comment]
Well it certainly seems like there's a consensus that we want this kind of thing to go _somewhere_, so I'll finish building this out after reading through @paulcsmith 's previous work and get us something that we can more formally review and (hopefully) merge!

Thanks, everyone!

**Comment by stephendolan** [comment]
Just a quick update since this has gone kind of stale. I've recently been working on a "Learn" section revamp where these kinds of cookbooks can go, and will likely implement this in a section there once I can merge it into the branch.

**Comment by stephendolan** [comment]
Closing this for now. I'd like to get the "Learn" section revamped and likely take a fresh swing at this. We can also have a bit of a broader discussion about where this should go once there's something more real to play with.

**Pull request closed without merging**
