### PR TITLE
Trading markd for cmark

### LINKED ISSUE #184: Try out this new markdown lib!
https://github.com/amauryt/cr-cmark-gfm

### PR DESCRIPTION
**Pull request by jwoertink**
Fixes #184 

This PR removes markd in favor of cmark which has full GFM. Markd has an open issue https://github.com/icyleaf/markd/issues/4 for adding GFM, but it currently doesn't support adding tables. 

Also in this PR, I've added a simple table with a few simple styles to show that we can now use them to clean up some of our docs.

 BEFORE:
Screen Shot 2020-09-11 at 1 15 19 PM

AFTER:
Screen Shot 2020-09-11 at 1 27 26 PM

Everything still renders as normal
Screen Shot 2020-09-11 at 1 27 44 PM

### CODE REVIEW

**Comment by jwoertink** [comment]
My guess is that deploy failed because heroku needs cmake. I wonder if that will require an update to the buildpack or something 🤔

**Review by paulcsmith — APPROVED** [review]
Once Heroku is working this LGTM!

**Comment by jwoertink** [comment]
Ok, I don't know why it passed last time, but now it's failing to build but deployed fine.... I opened this issue https://github.com/amauryt/cr-cmark-gfm/issues/4 to see if we can somehow skip building the man pages so we don't have to include python just for this.

**Comment by jwoertink** [comment]
ugh... it's toying with me. The CI passes and the deploy fails 😂

**Pull request merged**
