### PR TITLE
fix typo: rending -> rendering

### PR DESCRIPTION
**Pull request by ryanwood**

### CODE REVIEW

**Review by jwoertink — APPROVED** [review]
lol. There's a high probability that these typos are my bad 😬

**Comment by ryanwood** [comment]
It's all good. Happy to help. I'm a Ruby/Rails guy since 2005 and just discovered Crystal and Lucky. Enjoying reading through the guides. Really good stuff!

**Comment by jwoertink** [comment]
Nice! Same for me. Rails 1.1.6 was my first version (cue nostalgia). We're glad to have you! Welcome to Lucky 🎉

**Comment by ryanwood** [comment]
My first production site on Rails launched on 0.13. Sooooo old. 😉 Good to meet you.

**Pull request merged**
