### PR TITLE
moved guide redirects to a fallback to catch nested route changes

### PR DESCRIPTION
**Pull request by jwoertink**
Going to `/guides/database/querying` was throwing a 404 because it would never match this redirect path. Moving this to a `fallback` route now lets us handle all redirects regardless of their nesting. 

`request.path` will look like `"/guides/overview"` or `"/guides/database/querying"` so we just remove the guides part, and do the lookup.

### CODE REVIEW

**Review by paulcsmith — COMMENTED** [review]
I left a note in Gitter but I think we should move all the redirects to a LegacyRedirectHandler so we can put all the redirects in one spot. That way we can also use the fallback for something else if we need it later

**Comment by jwoertink** [comment]
Cool. Sounds good.

**Comment by jwoertink** [comment]
not sure why that build failed.

**Review by paulcsmith — APPROVED** [review]
Perfect!

**Pull request merged**
